@echo off
title mat_make
set /p mat_name=Enter material name: 
set mat_path=..\res\materials\%mat_name%
echo Making material "%mat_name%"...
python mat_make.py %mat_path%
if not errorlevel 0 echo Failed to pack textures...
set nvtt_export="C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe"
if exist %mat_path%\bbbx.png (
	%nvtt_export% %mat_path%\bbbx.png -o %mat_path%\bbbx.dds -f 26 -t 0 -q 3 --mips --mip-filter 1 --mip-gamma-correct --no-mip-pre-alpha --save-flip-y --dxt10
	if errorlevel 0 (
		echo Generated bbbx.dds
	) else echo Failed to generate bbbx.dds...
	echo Deleting bbbx.png...
	del %mat_path%\bbbx.png
) else echo Did not generate bbbx.dds...
if exist %mat_path%\nnnh.png (
	%nvtt_export% %mat_path%\nnnh.png -o %mat_path%\nnnh.dds -f 25 -t 0 -q 3 --mips --mip-filter 1 --no-mip-gamma-correct --no-mip-pre-alpha --save-flip-y --dxt10
	if errorlevel 0 (
		echo Generated nnnh.dds
	) else echo Failed to generate nnnh.dds...
	echo Deleting nnnh.png...
	del %mat_path%\nnnh.png
) else echo Did not generate nnnh.dds...
if exist %mat_path%\rmax.png (
	%nvtt_export% %mat_path%\rmax.png -o %mat_path%\rmax.dds -f 26 -t 0 -q 3 --mips --mip-filter 1 --no-mip-gamma-correct --no-mip-pre-alpha --save-flip-y --dxt10
	if errorlevel 0 (
		echo Generated rmax.dds
	) else echo Failed to generate rmax.dds...
	echo Deleting rmax.png...
	del %mat_path%\rmax.png
) else echo Did not generate rmax.dds...
echo Done!